#ifndef __DEFINE_H__
#define __DEFINE_H__

#include "..\include\public.h"

enum DB_CLASS_TYPE 
{
	DB_CLASS_TYPE_WIZARD = 0x0,
	DB_CLASS_TYPE_KNIGHT = 0x10,
	DB_CLASS_TYPE_ELF = 0x20,
	DB_CLASS_TYPE_MAGUMSA = 0x30,
	DB_CLASS_TYPE_DARKLORD = 0x40,
	DB_CLASS_TYPE_SUMMONER = 0x50,
	DB_CLASS_TYPE_MONK = 0x60,
	DB_CLASS_TYPE_LANCER = 0x70,
};

enum AMS 
{
	AM_NONE = 0x0,
	AM_STANDBY = 0x0,
	AM_ACTIVE = 0x1,
};

#define LOG_PRINT					1
//#define DEBUG_IOCP_LOG

#define ST_JOINSERVER				0	
#define ST_GAMESERVER				1	

#define DEFMAPSERVERPORT			55900		
#define DEFJOINSERVERPORT			55970		
#define DEFDATASERVERPORT			55960		
#define DEFEXDBSERVERPORT			55906		

#define MAX_CHAT					60
#define MAX_GUILDNOTICE				60
#define MAX_IDSTRING				10

#define MAX_ITEMLEVEL				15
#define MAX_ZEN						2000000000

#define MAXUSERCHARACTER			5

#define MAX_GUILDNAMESTRING			8
#define MAX_GUILDMARKSIZE			32

#define MAX_DBEQUIPMENT				120
#define MAX_DBINVENTORY				3792
#define MAX_ITEMDBBYTE				16

#define ITEM_BUFFER_SIZE			12
#define MONEY_BUFFER_SIZE			4

#define MAX_WAREHOUSEDBSIZE			3840
#define MAX_WAREHOUSEITEMS			(8*15)

#define MAX_EQUIPMENT				12
#define MAX_INVENTORY				237
#define INVENTORY_EXT4_SIZE			204

#define ITEM_BITSHIFT				9

#define MAX_DBMAGIC					(MAX_MAGIC*3)
#define MAX_DBQUEST					50

#define MAX_EXTENDINVENTORY			2
#define MAX_EXTENDWAREHOUSE			1

#define MAX_AB_JOINUSERINFO			200
#define MAX_AB_OBELISK_INFO			5

#endif

