//----------------------------------------------------------------------------
// 서버와 클라이언트가 공유하는 헤더 정의
//----------------------------------------------------------------------------
#ifndef __PUBLIC_H__
#define __PUBLIC_H__

#ifndef GAME_VERSION
#include "define.h"
#endif

//----------------------------------------------------------------------------
// 캐릭터 번호
enum ClassNumber
{
	CLASS_WIZARD,
	CLASS_KNIGHT,
	CLASS_ELF,
	CLASS_MAGUMSA,
	CLASS_DARKLORD, 
	CLASS_SUMMONER,
	CLASS_MONK,
	CLASS_LANCER
};


//#define MAX_MAGIC	20	// 사용자당 최대 마법 개수
//#ifdef ADD_NEW_SKILL_FOR_CASTLE_01_20041116// 공성전 패치 때 마법개수 늘림
#define MAX_MAGIC	150//60	// 사용자당 최대 마법 개수
//#endif

#define MAX_TOTALMAGIC100	// 마법최대 개수

#define DEF_DARKLORD_LEVEL	1	// 다크로드 캐릭터 생성시 기본 레벨
//----------------------------------------------------------------------------
// 저항력 번호
// -1: 없음, 0: 얼음, 1: 독, 2:번개, 3:불, 4:땅, 5:바람, 6:물
#define RESISTANCE_COLD0
#define RESISTANCE_POISON	1
#define RESISTANCE_THUNDER	2
#define RESISTANCE_FIRE3

#define RESISTANCE_EARTH	4
#define RESISTANCE_WIND5
#define RESISTANCE_WATER	6

//#ifdef ADD_MASTER_LEVEL_SKILL_SYSTEM_ACTIVE_20080107	// MAX_SKILL 수정
#define MAX_SKILL	600
//#endif


// View 상태
#define STATE_NONE	0	//  보통.
#define STATE_POISON0x00000001  //  독 걸린상태.
#define STATE_FREEZE0x00000002  //  얼음 걸린상태.
#define STATE_ATTACK0x00000004  //  공격력 증가.
#define STATE_DEFENSE0x00000008  //  방어력 증가.
#define STATE_ADD_LIFE0x00000010	//  생명력 증가.
#define STATE_HARDEN0x00000020	//  석화.
#define STATE_REDUCE_DEFENSE0x00000040	//  방어감소(마검사)	(몬스터 스킬도 같이 사용)
#define STATE_REDUCE_ATTACKDAMAGE	0x00000080	//  공격감소(법사)


#define STATE_REDUCE_MAGICDEFENSE	0x00000100	//  방어력증가(법사)
#define STATE_REDUCE_MAGICPOWER0x00000200	//  마법 능력 감소 (몬스터 스킬)
#define STATE_ADD_AG0x00000400	//  AG증가 속도 향상
#define STATE_ADD_CRITICAL_DAMAGE	0x00000800	//  크리티컬 데미지 증가

//#ifdef ADD_AUTHORITY_CODE_OF_EVENT_GM_20050602
#define STATE_ADD_GM_MARK	        0x01000000	//  GM 마크 스킨 추가
//#endif

#define STATE_IMMUNE_TO_MAGIC0x00000080	// 마법방어 무적(몹한테만.)	(STATE_REDUCE_ATTACKDAMAGE = 법사, 소울바리어)
#define STATE_IMMUNE_TO_HARM0x00000008	// 물리방어 무적(몹한테만.)	(STATE_DEFENSE = 요정, 방어력향상)


//#ifdef ADD_NEW_SKILL_FOR_CASTLE_01_20041116
#define STATE_BRAND_OF_SKILL0x00000200	// 다크로드가 보장하는 기술 브랜드 ^^
#define STATE_STUNED0x00001000	// 스턴 걸린 상태.
#define STATE_ADD_MANA0x00002000	// 마나 증가.
#define STATE_CLOAKING0x00004000	// 투명 상태.
#define STATE_BLESS_POTION	0x00008000	// 축복의 물약.
#define STATE_SOUL_POTION	0x00010000	// 영혼의 물약.
#define STATE_REMOVAL_MAGIC	0x00100000	// 마법 해제.
//#endif

//#ifdef ADD_NEW_MONSTER_SYSTEM_01_20050714
#define STATE_IMMUNE_TO_SKILL0x00200000	// 특정 스킬에 IMMUNE 상태
//#endif

//#ifdef ADD_SKILL_MUSE_ELF_INFINITYARROW_20060406
#define STATE_INFINITY_ARROW0x04000000	// 인피니티 애로우(뮤즈엘프) 스킬
//#endif

//#ifdef CASTLE_NPC_GATE_WORK_20041206
#define STATE_CASTLE_GATE	0x00020000	// 성문의 여닫힌 상태
//#endif
//#ifdef CASTLE_NPC_CROWN_WORK_20041210
#define STATE_CASTLE_CROWN	0x00020000	// 왕관의 등록 중 상태
//#endif

//#ifdef MU_CASTLESIEGE_JOINSIDE_VIEWPORT_20041209
#define STATE_JOIN_SIDE_DEFEND0x00040000	// 공성전 시 공/수 구분
#define STATE_JOIN_SIDE_ATTACK0x00080000	// 공성전 시 공/수 구분 - 공성 01
//#endif

//#ifdef MODIFY_CASTLESIEGE_IDENTIFICATION_20051012
#define STATE_JOIN_SIDE_ATTACK_2	0x00400000	// 공성전 시 공/수 구분 - 공성 02
#define STATE_JOIN_SIDE_ATTACK_3	0x00800000	// 공성전 시 공/수 구분 - 공성 03
//#endif


//#ifdef ADD_NPC_SHADOW_PHANTOM_20050616
#define STATE_NPC_HELP              0x02000000  // 쉐도우 팬텀 공격력 향상 & 방어력 향상 스킬 상태
//#endif

//#ifdef CRYWOLF_NPC_WORK_20050912
#define STATE_BESERKER	0x00800000	// BERSERKER 상태

#define STATE_CRYWOLF_NPC_HIDE	0x10000000	// 크라이울프 ONLY - NPC HIDE 상태

#define STATE_CRYWOLF_STATUE_SHIELD1	0x00000001	// 늑대의 신상 ONLY - 1단계 방어막 생성 상태
#define STATE_CRYWOLF_STATUE_SHIELD2	0x00000002	// 늑대의 신상 ONLY - 2단계 방어막 생성 상태
#define STATE_CRYWOLF_STATUE_SHIELD3	0x00000004	// 늑대의 신상 ONLY - 3단계 방어막 생성 상태
#define STATE_CRYWOLF_STATUE_SHIELD4	0x00000008	// 늑대의 신상 ONLY - 4단계 방어막 생성 상태
#define STATE_CRYWOLF_STATUE_SHIELD5	0x00000100	// 늑대의 신상 ONLY - 5단계 방어막 생성 상태

#define STATE_CRYWOLF_ALTAR_ENABLE0x00010000	// 늑대의 제단 ONLY - 계약 가능 상태
#define STATE_CRYWOLF_ALTAR_DISABLE0x00020000	// 늑대의 제단 ONLY - 계약 불능 상태
#define STATE_CRYWOLF_ALTAR_CONTRACTED	0x00040000	// 늑대의 제단 ONLY - 계약 되어 있는 상태
#define STATE_CRYWOLF_ALTAR_ATTEMPT0x00080000	// 늑대의 제단 ONLY - 계약 시도 상태
#define STATE_CRYWOLF_ALTAR_OCCUFIED	0x00100000	// 늑대의 제단 ONLY - 점령 당한 상태
//#endif

//#ifdef PCBANG_POINT_SYSTEM_20070206// 인장 버퍼
#define STATE_SEAL_ITEM	0x08000000	// PC방 포인트 인장 아이템 
//#endif

//#ifdef ADD_PCS_MARK_OF_EXP_20070205
#define STATE_MARK_USE	0x08000000
//#endif // ADD_PCS_MARK_OF_EXP_20070205

//#ifdef ADD_EVENT_MAP_ILLUSION_TEMPLE_20070328	// 환영 사원 전용 스킬
#define STATE_ILLUSION_TEMPLE_PRODECTION0x00040000	// 보호의 주문
#define STATE_ILLUSION_TEMPLE_RESTRAINT	0x00080000	// 속박의 주문
//#endif

//#ifdef EXPAND_VIEWSKILLSTATE_WORD_TO_INT_20041122
#define DEL_VIEWSKILLSTATE( x, y )( x &= ~ y )
#define ADD_VIEWSKILLSTATE( x, y )( x |= y   )
//#endif

//ifdef CHARACTER_AUTO_RECUPERATION_SYSTEM_20050614
enum CHARACTER_AUTO_RECUPERATION_TIME
{
	CART_10_SEC = 1000 * 10,
	CART_15_SEC = 1000 * 15,
	CART_25_SEC = 1000 * 25,
};
enum HP_MP_AG_VALUE_PER_TIME
{
	VPT_HP_MP_AG_1_PER_1_SEC = 1,
	VPT_HP_MP_AG_5_PER_1_SEC = 5,
	VPT_HP_MP_AG_10_PER_1_SEC = 10
};
//#endif

//#ifdef DARKLORD_WORK
enum eSkillType
{
	AT_SKILL_POISON = 0x1,
	AT_SKILL_METEO = 0x2,
	AT_SKILL_THUNDER = 0x3,
	AT_SKILL_FIREBALL = 0x4,
	AT_SKILL_FLAME = 0x5,
	AT_SKILL_TELEPORT = 0x6,
	AT_SKILL_SLOW = 0x7,
	AT_SKILL_STORM = 0x8,
	AT_SKILL_EVIL = 0x9,
	AT_SKILL_HELL = 0xA,
	AT_SKILL_POWERWAVE = 0xB,
	AT_SKILL_FLASH = 0xC,
	AT_SKILL_BLAST = 0xD,
	AT_SKILL_INFERNO = 0xE,
	AT_SKILL_TARGET_TELEPORT = 0xF,
	AT_SKILL_MAGICDEFENSE = 0x10,
	AT_SKILL_ENERGYBALL = 0x11,
	AT_SKILL_BLOCKING = 0x12,
	AT_SKILL_SWORD1 = 0x13,
	AT_SKILL_SWORD2 = 0x14,
	AT_SKILL_SWORD3 = 0x15,
	AT_SKILL_SWORD4 = 0x16,
	AT_SKILL_SWORD5 = 0x17,
	AT_SKILL_CROSSBOW = 0x18,
	AT_SKILL_BOW = 0x19,
	AT_SKILL_HEALING = 0x1A,
	AT_SKILL_DEFENSE = 0x1B,
	AT_SKILL_ATTACK = 0x1C,
	AT_SKILL_CALLMON1 = 0x1E,
	AT_SKILL_CALLMON2 = 0x1F,
	AT_SKILL_CALLMON3 = 0x20,
	AT_SKILL_CALLMON4 = 0x21,
	AT_SKILL_CALLMON5 = 0x22,
	AT_SKILL_CALLMON6 = 0x23,
	AT_SKILL_CALLMON7 = 0x24,
	AT_SKILL_WHEEL = 0x29,
	AT_SKILL_BLOWOFFURY = 0x2A,
	AT_SKILL_STRIKE = 0x2B,
	AT_SKILL_KNIGHTSPEAR = 0x2F,
	AT_SKILL_KNIGHTADDLIFE = 0x30,
	AT_SKILL_KNIGHTDINORANT = 0x31,
	AT_SKILL_ELFHARDEN = 0x33,
	AT_SKILL_PENETRATION = 0x34,
	AT_SKILL_DEFENSEDOWN = 0x37,
	AT_SKILL_SWORD6 = 0x38,
	AT_SKILL_5CROSSBOW = 0x36,
	AT_SKILL_EXPPOISON = 0x26,
	AT_SKILL_EXPICE = 0x27,
	AT_SKILL_EXPHELL = 0x28,
	AT_SKILL_EXPHELL_START = 0x3A,
	AT_SKILL_IMPROVE_AG_REFILL = 0x35,
	AT_SKILL_DEVILFIRE = 0x32,
	AT_SKILL_COMBO = 0x3B,
	AT_SKILL_SPEAR = 0x3C,
	AT_SKILL_FIREBURST = 0x3D,
	AT_SKILL_DARKHORSE_ATTACK = 0x3E,
	AT_SKILL_RECALL_PARTY = 0x3F,
	AT_SKILL_ADD_CRITICALDAMAGE = 0x40,
	AT_SKILL_ELECTRICSPARK = 0x41,
	AT_SKILL_LONGSPEAR = 0x42,
	AT_SKILL_RUSH = 0x2C,
	AT_SKILL_JAVALIN = 0x2D,
	AT_SKILL_DEEPIMPACT = 0x2E,
	AT_SKILL_ONE_FLASH = 0x39,
	AT_SKILL_DEATH_CANNON = 0x49,
	AT_SKILL_SPACE_SPLIT = 0x4A,
	AT_SKILL_BRAND_OF_SKILL = 0x4B,
	AT_SKILL_STUN = 0x43,
	AT_SKILL_REMOVAL_STUN = 0x44,
	AT_SKILL_ADD_MANA = 0x45,
	AT_SKILL_INVISIBLE = 0x46,
	AT_SKILL_REMOVAL_INVISIBLE = 0x47,
	AT_SKILL_REMOVAL_MAGIC = 0x48,
	AT_SKILL_FENRIR_ATTACK = 0x4C,
	AT_SKILL_SUMMON = 0xC8,
	AT_SKILL_IMMUNE_TO_MAGIC = 0xC9,
	AT_SKILL_IMMUNE_TO_HARM = 0xCA,
};

enum eOptionType
{
	AT_IMPROVE_DAMAGE = 0x50,
	AT_IMPROVE_MAGIC = 0x51,
	AT_IMPROVE_BLOCKING = 0x52,
	AT_IMPROVE_DEFENSE = 0x53,
	AT_LUCK = 0x54,
	AT_LIFE_REGENERATION = 0x55,
	AT_IMPROVE_LIFE = 0x56,
	AT_IMPROVE_MANA = 0x57,
	AT_DECREASE_DAMAGE = 0x58,
	AT_REFLECTION_DAMAGE = 0x59,
	AT_IMPROVE_BLOCKING_PERCENT = 0x5A,
	AT_IMPROVE_GAIN_GOLD = 0x5B,
	AT_EXCELLENT_DAMAGE = 0x5C,
	AT_IMPROVE_DAMAGE_LEVEL = 0x5D,
	AT_IMPROVE_DAMAGE_PERCENT = 0x5E,
	AT_IMPROVE_MAGIC_LEVEL = 0x5F,
	AT_IMPROVE_MAGIC_PERCENT = 0x60,
	AT_IMPROVE_ATTACK_SPEED = 0x61,
	AT_IMPROVE_GAIN_LIFE = 0x62,
	AT_IMPROVE_GAIN_MANA = 0x63,
	AT_PLUS_WING_MAXLIFE = 0x64,
	AT_PLUS_WING_MAXMANA = 0x65,
	AT_PLUS_ONE_PERCENT_DAMAGE = 0x66,
	AT_IMPROVE_AG_MAX = 0x67,
	AT_DAMAGE_ABSORB = 0x68,
	AT_PLUS_WING_ADD_LEADERSHIP = 0x69,
	AT_PLUS_FENRIR_INCREASE_LAST_DAMAGE = 0x6A,
	AT_PLUS_FENRIR_DECREASE_LAST_DAMAGE = 0x6B,
	AT_5PER_IGNORE_DEFENSE = 0x6C,
	AT_5PER_ATTACK_TURNING = 0x6D,
	AT_RECOVER_100PER_LIFE = 0x6E,
	AT_RECOVER_100PER_MASIC = 0x6F,
	AT_PLUS_ILLUSION_FENRIR_OPTION = 0x70,
	AT_IMPROVE_CURSE = 0x71,
	AT_4PER_IGNORE_DEFENSE = 0x72,
	AT_4PER_RECOVER_100PER_LIFE = 0x73,
	AT_4PER_DOUBLE_DAMAGE = 0x74,
	AT_EXCELLENT_OPTION_EX_WEAPON_1EA = 0x75,
	AT_EXCELLENT_OPTION_EX_WEAPON_2EA = 0x76,
	AT_EXCELLENT_OPTION_EX_WEAPON_3EA = 0x77,
	AT_EXCELLENT_OPTION_EX_ARMOR_1EA = 0x78,
	AT_EXCELLENT_OPTION_EX_ARMOR_2EA = 0x79,
	AT_EXCELLENT_OPTION_EX_ARMOR_3EA = 0x7A,
	AT_ATTACK1 = 0x78,
	AT_ATTACK2 = 0x79,
	AT_STAND1 = 0x7A,
	AT_STAND2 = 0x7B,
	AT_MOVE1 = 0x7C,
	AT_MOVE2 = 0x7D,
	AT_DAMAGE1 = 0x7E,
	AT_DIE1 = 0x7F,
	AT_SIT1 = 0x80,
	AT_POSE1 = 0x81,
	AT_HEALING1 = 0x82,
	AT_GREETING1 = 0x83,
	AT_GOODBYE1 = 0x84,
	AT_CLAP1 = 0x85,
	AT_GESTURE1 = 0x86,
	AT_DIRECTION1 = 0x87,
	AT_UNKNOWN1 = 0x88,
	AT_CRY1 = 0x89,
	AT_CHEER1 = 0x8A,
	AT_AWKWARD1 = 0x8B,
	AT_SEE1 = 0x8C,
	AT_WIN1 = 0x8D,
	AT_SMILE1 = 0x8E,
	AT_SLEEP1 = 0x8F,
	AT_COLD1 = 0x90,
	AT_AGAIN1 = 0x91,
	AT_RESPECT1 = 0x92,
	AT_SALUTE1 = 0x93,
	AT_RUSH1 = 0x94,
	AT_SET_RING_OPTION_ADD_SKILLDAMAGE = 0x95,
	AT_SET_OPTION_IMPROVE_STRENGTH = 0xA0,
	AT_SET_OPTION_IMPROVE_DEXTERITY = 0xA1,
	AT_SET_OPTION_IMPROVE_ENERGY = 0xA2,
	AT_SET_OPTION_IMPROVE_VITALITY = 0xA3,
	AT_SET_OPTION_IMPROVE_LEADERSHIP = 0xA4,
	AT_SET_OPTION_IMPROVE_MINATTACKDAMAGE = 0xA5,
	AT_SET_OPTION_IMPROVE_MAXATTACKDAMAGE = 0xA6,
	AT_SET_OPTION_IMPROVE_MAGICDAMAGE = 0xA7,
	AT_SET_OPTION_IMPROVE_DAMAGE = 0xA8,
	AT_SET_OPTION_IMPROVE_ATTACKRATE = 0xA9,
	AT_SET_OPTION_IMPROVE_DEFENCE = 0xAA,
	AT_SET_OPTION_IMPROVE_MAXLIFE = 0xAB,
	AT_SET_OPTION_IMPROVE_MAXMANA = 0xAC,
	AT_SET_OPTION_IMPROVE_MAXAG = 0xAD,
	AT_SET_OPTION_IMPROVE_AG_VALUE = 0xAE,
	AT_SET_OPTION_IMPROVE_CRITICALDAMAGE_SUCCESS = 0xAF,
	AT_SET_OPTION_IMPROVE_CRITICALDAMAGE = 0xB0,
	AT_SET_OPTION_IMPROVE_EX_DAMAGE_SUCCESS = 0xB1,
	AT_SET_OPTION_IMPROVE_EX_DAMAGE = 0xB2,
	AT_SET_OPTION_IMPROVE_SKILLDAMAGE = 0xB3,
	AT_SET_OPTION_DOUBLE_DAMAGE = 0xB4,
	AT_SET_OPTION_DEFENCE_IGNORE = 0xB5,
	AT_SET_OPTION_IMPROVE_SHIELD_DEFENCE = 0xB6,
	AT_SET_OPTION_TWO_HAND_SWORD_IMPROVE_DAMAGE = 0xB7,
	AT_SET_OPTION_IMPROVE_ATTACKDAMAGE_WITH_STR = 0xB8,
	AT_SET_OPTION_IMPROVE_ATTACKDAMAGE_WITH_DEX = 0xB9,
	AT_SET_OPTION_IMPROVE_DEFENCE_WITH_DEX = 0xBA,
	AT_SET_OPTION_IMPROVE_DEFENCE_WITH_VIT = 0xBB,
	AT_SET_OPTION_IMPROVE_MAGICDAMAGE_WITH_ENERGY = 0xBC,
	AT_SET_OPTION_ICE_MASTERY = 0xBD,
	AT_SET_OPTION_POSION_MASTERY = 0xBE,
	AT_SET_OPTION_THUNDER_MASTERY = 0xBF,
	AT_SET_OPTION_FIRE_MASTERY = 0xC0,
	AT_SET_OPTION_EARTH_MASTERY = 0xC1,
	AT_SET_OPTION_WIND_MASTERY = 0xC2,
	AT_SET_OPTION_WATER_MASTERY = 0xC3,
	AT_SET_IMPROVE_STRENGTH = 0xC4,
	AT_SET_IMPROVE_DEXTERITY = 0xC5,
	AT_SET_IMPROVE_ENERGY = 0xC6,
	AT_SET_IMPROVE_VITALITY = 0xC7,
};

//#ifdef ADD_JEWEL_OF_HARMONY_SYSTEM_20060530
enum eJewelOfHarmonyItemOption
{
	// 공통
	AT_JEWELOFHARMONY_NOT_STRENGTHEN_ITEM = 0,	// 효과 없음 : 강화되지 않은 아이템

	// 무기류 옵션
	AT_JEWELOFHARMONY_WEAPON_IMPROVE_MINATTACKDAMAGE = 1,	// 최소 공격력 상승 (값)
	AT_JEWELOFHARMONY_WEAPON_IMPROVE_MAXATTACKDAMAGE = 2,	// 최대 공격력 상승 (값)
	AT_JEWELOFHARMONY_WEAPON_DECREASE_REQUIRE_STR = 3,	// 필요 힘 감소 (값)
	AT_JEWELOFHARMONY_WEAPON_DECREASE_REQUIRE_DEX = 4,	// 필요 민첩 감소 (값)
	AT_JEWELOFHARMONY_WEAPON_IMPROVE_ATTACKDAMAGE_BOTH = 5,	// 공격력 상승 (최소,최대) (값)
	AT_JEWELOFHARMONY_WEAPON_IMPROVE_CRITICALDAMAGE = 6,	// 크리티컬 데미지 상승 (값)
	AT_JEWELOFHARMONY_WEAPON_IMPROVE_SKILLDAMAGE = 7,	// 스킬 공격력 상승 (값)
	AT_JEWELOFHARMONY_WEAPON_IMPROVE_ATTACKSUCCESRATE_PVP = 8,	// 공격 성공율 상승 (PVP)  (값)
	AT_JEWELOFHARMONY_WEAPON_DECREASE_SD_RATE = 9,	// SD 감소율 상승 (실드 데미지 흡수율 감소. 직접 HP에 주는 데미지가 증가)  (값)
	AT_JEWELOFHARMONY_WEAPON_IMPROVE_IGNORE_SD_RATE = 10,  // 공격시 SD 무시 확률 상승 : SD를 무시하고 직접 HP에 데미지를 가한다.  (값)

	// 지팡이류
	AT_JEWELOFHARMONY_STAFF_IMPROVE_MAGICDAMAGE = 1,	// 마력 상승(값)
	AT_JEWELOFHARMONY_STAFF_DECREASE_REQUIRE_STR = 2,	// 필요 힘 감소 (값)
	AT_JEWELOFHARMONY_STAFF_DECREASE_REQUIRE_DEX = 3,	// 필요 민첩 감소 (값)
	AT_JEWELOFHARMONY_STAFF_IMPROVE_SKILLDAMAGE = 4,	// 스킬 공격력 상승 (값)
	AT_JEWELOFHARMONY_STAFF_IMPROVE_CRITICALDAMAGE = 5,	// 크리티컬 데미지 상승 (값)
	AT_JEWELOFHARMONY_STAFF_DECREASE_SD_RATE = 6,	// SD 감소율 상승 (실드 데미지 흡수율 감소. 직접 HP에 주는 데미지가 증가)  (값)//#endif
	AT_JEWELOFHARMONY_STAFF_IMPROVE_ATTACKSUCCESRATE_PVP = 7,	// 공격 성공율 상승 (PVP)  (값)
	AT_JEWELOFHARMONY_STAFF_IMPROVE_IGNORE_SD_RATE = 8,   // 공격시 SD 무시 확률 상승 : SD를 무시하고 직접 HP에 데미지를 가한다.  (값)

	// 방어구류
	AT_JEWELOFHARMONY_DEFENSE_IMPROVE_DEFENSE = 1,   // 방어력 상승 (값)
	AT_JEWELOFHARMONY_DEFENSE_IMPROVE_MAX_AG = 2,	// 최대 AG 상승 (값)
	AT_JEWELOFHARMONY_DEFENSE_IMPROVE_MAX_HP = 3,	// 최대 HP 상승 (값)
	AT_JEWELOFHARMONY_DEFENSE_IMPROVE_AUTO_REFILL_HP = 4,	// 생명력 자동 증가량 상승
	AT_JEWELOFHARMONY_DEFENSE_IMPROVE_AUTO_REFILL_MP = 5,	// 마나 자동 증가량 상승
	AT_JEWELOFHARMONY_DEFENSE_IMPROVE_BLOCKSUCCESRATE_PVP = 6,	// 방어 성공률 상승 (PVP) 값
	AT_JEWELOFHARMONY_DEFENSE_IMPROVE_DAMAGE_DECREASE = 7,	// 데미지 감소 % 상승
	AT_JEWELOFHARMONY_DEFENSE_IMPROVE_SD_RATE = 8   // SD 비율 상승 ( PVP시에 SD 비율이 높아짐 )
};



#endif

